### ISSUE TITLE
standalone test failure on aarch64-windows in Release: mix_c_files

### ISSUE THREAD

**Issue by kubkon** [ziglang/zig#13738]
### Zig Version

0.11.0-dev.449+665eba93c

### Steps to Reproduce and Observed Behavior

```
$ zig.exe build test-standalone --search-prefix llvm -Dstatic-llvm -Dskip-non-native
error: lld-link: undefined symbol: ldexpl
>>> referenced by stage3\lib\zig\libc\mingw\math\cbrtl.c
>>>               mingwex.lib(cbrtl.obj)

error: test...
error: The following command exited with error code 1:
C:\Users\kubko\dev\zig\stage3\bin\zig.exe build-exe C:\Users\kubko\dev\zig\test\standalone\mix_c_files\main.zig -cflags -std=c11 -- C:\Users\kubko\dev\zig\test\standalone\mix_c_files\test.c -lc -OReleaseSafe --cache-dir C:\Users\kubko\dev\zig\test\standalone\mix_c_files\zig-cache --global-cache-dir C:\Users\kubko\AppData\Local\zig --name test --enable-cache
error: the following build command failed with exit code 1:
C:\Users\kubko\dev\zig\test\standalone\mix_c_files\zig-cache\o\d9f2386dfa0bae9f7994c5b2f16d2cbb\build.exe C:\Users\kubko\dev\zig\stage3\bin\zig.exe C:\Users\kubko\dev\zig\test\standalone\mix_c_files C:\Users\kubko\dev\zig\test\standalone\mix_c_files\zig-cache C:\Users\kubko\AppData\Local\zig test -Drelease-safe
The following command exited with error code 1 (expected 0):
cd C:\Users\kubko\dev\zig && stage3\bin\zig.exe build --build-file C:\Users\kubko\dev\zig\test\standalone\mix_c_files\build.zig test -Drelease-safe
error: UnexpectedExitCode
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:277:17: 0x7ff629b4a9eb in runCommand (build.exe.obj)
                return error.UnexpectedExitCode;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:183:5: 0x7ff629b20b43 in make (build.exe.obj)
    try runCommand(
    ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:3665:9: 0x7ff629abfe67 in make (build.exe.obj)
        try self.makeFn(self);
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:510:9: 0x7ff629a9c92f in makeOneStep (build.exe.obj)
        try s.make();
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:504:17: 0x7ff629a9c85f in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:504:17: 0x7ff629a9c85f in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:465:13: 0x7ff629a9c543 in make (build.exe.obj)
            try self.makeOneStep(s);
            ^
C:\Users\kubko\dev\zig\stage3\lib\zig\build_runner.zig:225:21: 0x7ff629a9ed43 in main (build.exe.obj)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
C:\Users\kubko\dev\zig\zig-cache\o\dfa7cbfd57ef72576b5647ecb1a65d04\build.exe C:\Users\kubko\dev\zig\stage3\bin\zig.exe C:\Users\kubko\dev\zig C:\Users\kubko\dev\zig\zig-cache C:\Users\kubko\AppData\Local\zig test-standalone --search-prefix C:\Users\kubko\dev\zig-llvm -Dstatic-llvm -Dskip-non-native
```

### Expected Behavior

Tests should link correctly and run.

**Comment by coin3x** [comment]
This seems to have been fixed by #13854.

**Comment by kubkon** [comment]
If that is indeed the case, then awesome. Feel free to re-enable the test case and submit a PR. :-)

**Comment by andrewrk** [comment]
Tests re-enabled in 4832677c3bce61725c67306c4683921296abdff9.

**Comment by hronro** [comment]
Seems this bug still exists in v0.10.1.

Why the fix is not backported to v0.10.1?
