### ISSUE TITLE
translate-c test case "typedef void" is failing in the llvm16 branch

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14557]
https://github.com/ziglang/zig/blob/09cee1d5e34dd4187242a693c2d7b5a9d1e689b1/test/translate_c.zig#L878-L885

```
========= Expected to find: ===================
pub extern fn fun(a: ?*Foo) void;
========= But file does not contain it: =======
pub extern fn fun(a: ?*Foo) Foo;

```

perhaps caused by this diff:

```diff
-struct ZigClangQualType ZigClangTypeOfType_getUnderlyingType(const struct ZigClangTypeOfType *self) {
+struct ZigClangQualType ZigClangTypeOfType_getUnmodifiedType(const struct ZigClangTypeOfType *self) {
     auto casted = reinterpret_cast<const clang::TypeOfType *>(self);
-    return bitcast(casted->getUnderlyingType());
+    return bitcast(casted->getUnmodifiedType());
 }
```

`getUnderlyingType` was removed, and I replaced it with `getUnmodifiedType`, but perhaps that was the wrong replacement.

Relevant LLVM commit: https://github.com/llvm/llvm-project/commit/60727d856927383daf304fcf8f19fcc8ade828ad

**Comment by nektro** [comment]
does `return bitcast(casted->desugar());` work?

**Comment by Vexu** [comment]
Fixed by 72443fb88cfddad8a58868c150eaf5818826cb21.

**Comment by nektro** [comment]
thats the wrong test

**Comment by Vexu** [comment]
The original test case didn't need to be changed.

**Comment by andrewrk** [comment]
I'm still getting this output locally after building 72443fb88cfddad8a58868c150eaf5818826cb21:

```
$ stage3/bin/zig build test-translate-c test-run-translated-c

========= Expected to find: ===================
pub extern fn fun(a: ?*Foo) void;
========= But file does not contain it: =======
pub const Foo = anyopaque;
pub extern fn fun(a: ?*Foo) Foo;
```
