### ISSUE TITLE
Build error ``error: ELF flush failed: ReadFailed``

### ISSUE THREAD

**Issue by ChillerDragon** [ziglang/zig#24700]
```
[chiller@archlinux build]$ make
[ 36%] Built target zigcpp
[ 47%] Built target zig-wasm2c
[ 68%] Built target zig1
[ 94%] Built target zig2
[100%] Building stage3
install
└─ install zig
   └─ compile exe zig Debug native 1 errors
error: ELF flush failed: ReadFailed
error: the following command failed with 1 compilation errors:
/home/chiller/Desktop/git-extern/zig/build/zig2 build-exe -fallow-so-scripts --stack 48234496 /home/chiller/Desktop/git-extern/zig/build/zigcpp/libzigcpp.a /usr/lib/libclang-cpp.so.20.1 /usr/lib/liblldMinGW.so /usr/lib/liblldELF.so /usr/lib/liblldCOFF.so /usr/lib/liblldWasm.so /usr/lib/liblldMachO.so /usr/lib/liblldCommon.so -lLLVM-20 /usr/lib/libstdc++.so -lunwind -fno-sanitize-thread -ODebug -I /usr/include -I /usr/include -L /usr/lib --dep aro --dep aro_translate_c --dep build_options -Mroot=/home/chiller/Desktop/git-extern/zig/src/main.zig -Maro=/home/chiller/Desktop/git-extern/zig/lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=/home/chiller/Desktop/git-extern/zig/lib/compiler/aro_translate_c.zig -Mbuild_options=.zig-cache/c/7e8ed09042d22b740901c49824775438/options.zig -lc --cache-dir .zig-cache --global-cache-dir /home/chiller/.cache/zig --name zig --zig-lib-dir lib/ --listen=-

Build Summary: 2/5 steps succeeded; 1 failed
install transitive failure
└─ install zig transitive failure
   └─ compile exe zig Debug native 1 errors

error: the following build command failed with exit code 1:
.zig-cache/o/361cdf57e3c1ba71de5aa8c7a3d74ff8/build /home/chiller/Desktop/git-extern/zig/build/zig2 lib /home/chiller/Desktop/git-extern/zig .zig-cache /home/chiller/.cache/zig --seed 0x37c06596 -Zef6b9866b40c4cd4 --prefix /home/chiller/Desktop/git-extern/zig/build/stage3 -Dversion-string=0.15.0-dev.1415+82961a8c9 -Dtarget=native -Dcpu=native -Denable-llvm -Dconfig_h=/home/chiller/Desktop/git-extern/zig/build/config.h -Dno-langref -Doptimize=Debug
make[2]: *** [CMakeFiles/stage3.dir/build.make:73: stage3/bin/zig] Error 1
make[1]: *** [CMakeFiles/Makefile2:228: CMakeFiles/stage3.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
[chiller@archlinux build]$ clang --version
clang version 20.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[chiller@archlinux build]$ uname -a
Linux archlinux 6.15.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Aug 2025 01:20:06 +0000 x86_64 GNU/Linux
```

**Comment by ghost** [comment]
Same for me. I'm on 6.15.9-arch1-1, too.

**Comment by MylJa** [comment]
Same error here with unstable nixos

**Comment by ghost** [comment]
This is regression. Build works for commits prior to [742956865c0c55b6650d7b89d923b63ea11cde4f](https://github.com/ziglang/zig/commit/742956865c0c55b6650d7b89d923b63ea11cde4f).

**Comment by ghost** [comment]
Seems to have been fixed as of the current commit. @ChillerDragon could you confirm?

**Comment by rpkak** [comment]
I can confirm, that in ReleaseFast the error does not appear any more, but in Debug, there still is an assertion failure. So probably there is still UB in ReleaseFast.

**Comment by rpkak** [comment]
The assertion failure seems to be fixed in 0a1a738320219961c0809a92ac7607a5525aa33e.

**Comment by rpkak** [comment]
> The assertion failure seems to be fixed in [0a1a738](https://github.com/ziglang/zig/commit/0a1a738320219961c0809a92ac7607a5525aa33e).

Wrong: after deleting the zig cache, 0a1a738 now also has the assertion failure (probably a bug of zig's caching system).

The assertion failure still exists in `master` (d1917b5c3ac9b79425667dc75768e4f75389f635).

**Comment by ghost** [comment]
NixOS 25.05
Building [e98aeeb](https://github.com/ziglang/zig/commit/e98aeeb73fba942c8e061bb8158ed073a7b19e1d) in *Debug* throws `error: ELF flush failed: ReadFailed` (haven't tested other built types). On fedora 42 it succeeds (with -DZIG_SHARED_LLVM which is not relevant here?)
Building [dd4e25c](https://github.com/ziglang/zig/commit/dd4e25cf4410017cb113c0cb1c85c6e5c75729e3) in *Debug* and in *RelWithDebInfo* succeeds.

This is what i have in `nix shell` for zig:
`cmake ninja clang llvmPackages_20.libclang llvmPackages_20.llvm llvmPackages_20.lld libxml2 stdenv.cc.cc.lib`

**Comment by rpkak** [comment]
When you are compiling dd4e25cf4410017cb113c0cb1c85c6e5c75729e3, is the compiler you compile zig with or the compiler you newly compile Debug. When I compile a debug compiler with a debug compiler the assertion failure still exists.

**Comment by ozgrakkurt** [comment]
For any noobs like me having this issue, if you just want to make a dev build of zig and use it, using the "Option B: Use a Pre-Built Zig Binary" from the wiki works.

https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#option-b-use-a-pre-built-zig-binary

But had to also remove `-Dstatic-llvm` option from the command on my setup

**Comment by rpkak** [comment]
This diff seems to fix the assertion failure:

```diff
diff --git a/lib/std/Io/Writer.zig b/lib/std/Io/Writer.zig
index 1a08ed1653..aee1772587 100644
--- a/lib/std/Io/Writer.zig
+++ b/lib/std/Io/Writer.zig
@@ -381,7 +381,7 @@ pub fn writableSliceGreedy(w: *Writer, minimum_length: usize) Error![]u8 {
 ///
 /// If `preserve_len` is zero, this is equivalent to `writableSliceGreedy`.
 pub fn writableSliceGreedyPreserve(w: *Writer, preserve_len: usize, minimum_length: usize) Error![]u8 {
-    assert(w.buffer.len >= preserve_len + minimum_length);
+    assert(w.buffer.len >= @min(preserve_len, w.end) + minimum_length);
     while (w.buffer.len - w.end < minimum_length) {
         try drainPreserve(w, preserve_len);
     } else {
diff --git a/lib/std/compress/flate/Decompress.zig b/lib/std/compress/flate/Decompress.zig
index 2bb84a3289..2fc551c252 100644
--- a/lib/std/compress/flate/Decompress.zig
+++ b/lib/std/compress/flate/Decompress.zig
@@ -239,8 +239,6 @@ fn decodeSymbol(self: *Decompress, decoder: anytype) !Symbol {
 }

 fn streamDirect(r: *Reader, w: *Writer, limit: std.Io.Limit) Reader.StreamError!usize {
-    assert(w.buffer.len >= flate.max_window_len);
-    assert(w.unusedCapacityLen() >= flate.history_len);
     const d: *Decompress = @alignCast(@fieldParentPtr("reader", r));
     return streamFallible(d, w, limit);
 }
```

I haven't created a PR until now because removing assertions from a decompression algorithm, whose details I don't know, doesn't seem like a good idea. But I think the change in the assertion of writableSliceGreedyPreserve makes sense, independent of this issue, to make it more consistent with, e.g. drainPreserve (#24767).

**Comment by andrewrk** [comment]
> This diff seems to fix the assertion failure:

in that case, #24844 is relevant.

**Comment by andrewrk** [comment]
fix landed in af7e142485d422e1fdbff1dcfc6e95e4f9126453
