### ISSUE TITLE
Rename `anytype` to `anyval`

### ISSUE THREAD

**Issue by SpexGuy** [ziglang/zig#5893]
Sorry, this is kind of nitpicking, but it's been bothering me.

The value of a variable of type `anyerror` is some error.
The value of a variable of type `anyframe` is some frame.
The value of a variable of type `anytype` is usually not a type.

Said another way,
A variable that holds some unknown error is an `anyerror`.
A variable that holds some unknown frame is an `anyframe`.
A variable that holds some unknown type is a `type`.
A variable that holds some unknown value is an `anytype`?

`var` was a bad name because it was overloaded with the mutability specifier.  But aside from that, IMO it was an ok name.  I don't think we should restore it but I think `anytype` is also confusing.  `any` might be a good choice except that it is a common enough variable or function name that the language probably shouldn't reserve it.  `infer` was suggested previously, but doesn't convey that the type can change over the variable's lifetime.  Maybe `anyvalue`, `anyval`, or `vartype` would be better?

**Comment by Sobeston** [comment]
I agree, and personally like `anyvalue` and `anyval`.

**Comment by data-man** [comment]
Important part was missed - declaration.

```
i: u32 // i is u32 variable
T: type // T can be type only
writer: anytype // writer is variable with any type, not unknown value
```
What's problem?

**Comment by EleanorNB** [comment]
+1 for `anyval`. I think that's much better.

**Comment by timmyjose** [comment]
> I agree, and personally like `anyvalue` and `anyval`.

Seconded. I found it terribly confusing when the ZIg formatter started changing my `var`S to `anytype`S. I would have expectd `anytype` to really be a type, but it's apparently just the new name to `var`.

**Comment by timmyjose** [comment]
> Important part was missed - declaration.
> 
> ```
> i: u32 // i is u32 variable
> T: type // T can be type only
> writer: anytype // writer is variable with any type, not unknown value
> ```
> 
> What's problem?

Something like so:

```
const std = @import("std");

fn printAnyType(obj: anytype) void {
    std.debug.print("{}, {}, {}\n", .{ obj.@"foo", obj.@"bar", obj.@"baz" });
}

test "printAnyType" {
    printAnyType(.{ .foo = "Hello", .bar = 1, .baz = false });
}

```

where I would have assumed `anytype` to be a type, not a value. Instead, it is sort of like a generic object, a *value*. In a purely functional dependently-typed language like Idris, maybe types and values are truly equivalent, but in an imperative language, it feels jarring.

**Comment by loris-olsem** [comment]
+1 for ``anyvalue`` since we have ``anyerror`` not ``anyerr``, but ``anyval`` sounds nice too.

**Comment by rohlem** [comment]
My opinion:
A value of `anyerror` is an `error` value. `anyerror` is the "supertype" of all more specialized `error` types.
A value of `anyframe` is a `frame` value. `anyframe` is the "supertype" of all more specialized `frame` types.
A value of the proposed `anyvalue`/`anyval` will be... a `value` value. Which kind of makes sense, because Zig treats everything, including types, conceptually as values. But when asking "what types of value can I expect" the answer is "value values". It doesn't seem quite as intuitive to me.

Another option would be plain `any`. Then it's clear it's whatever you can think of - functions, types, values, whatever you can pass as an argument / bind to the name.
I think it's also clearer that `any` is even less specialized than `anyerror` and `anyframe`.

**Comment by AssortedFantasy** [comment]
I **hard** disagree with this.
Personally, I believe a type definition answers the question "What type is this?".

`a: anyerror` -> The type of `a` is any error.
`b: anyframe` -> The type of  `b` is any frame.
`c: anytype` -> The type of `c` is any type.
`d: u32` -> The type of `d` is u32.

Nothing is ambiguous, the only reason you have an ambiguity here is because you are omitting the "The type of" statement and transforming the statement around a bit (which is ususally fine) but for some reason you doing it incorrectly for anytype.

`d: u32` -> `d` is a `u32`
But instead of this: `c: anytype` -> `c` is an any type (which is a weird thing to say, but its correct)
You're saying this `c: anytype` -> `c` is any type. (wrong, and can be interpreted wrong as saying that `c` itself is a type).

Additionally there is a bit of a misunderstanding conflating values themselves to types to superclasses of types.

>A variable that holds some unknown value is an anytype?

A variable that hold some unknown value is just a redundant way of saying "a variable".
Up there, `d` is also has some unknown value, the value has nothing to do with it, you can clearly see why `anyvalue` is wrong below.

`e: anyvalue` -> The type of `e` is any value [ of any type?]

This suggests that [the type of] `e` could be a value like `2`. But obviously the type of `e` must still be a type (hence `anytype`).

Anyway for more on superclasses, `anyframe` isn't actually a specific type, it's a superclass where any specific `frame` type for each function can be transformed into it. Same for errors, `anyerror` is a superclass where any specific `error` enum type can be turned into it.

I understand why all this confusion specifically happens for `anytype` though because Zig treats types like values.  So you have to deal with strange (at first glance) statements like this.

`c: antype` -> `c` is an any type (including a type itself)

Then the statement "`c` is any type" isn't unambiguously wrong, because technically `c` could be a type.

Anyway I'm sorry if my response is long and convoluted, but please read through it again if you don't understand. I spent a long time thinking about why this was wrong but I couldn't quite put it into words. It might not be abundantly clear, but I assure you, `antype` is not ambiguous and is correct.

**Comment by EleanorNB** [comment]
@AssortedFantasy You seem to be putting a lot of weight on a specific translation of Zig syntax into English, and moreover on a specific syntactic ambiguity which this particular translation has. There are other ways of thinking, and many of them arrive at different places. Just because something makes sense to you doesn't mean it's the only or best possible way of thinking.
----
`anyerror` is the supertype of all errors.
`anyframe` is the supertype of all frames.
`anytype` is...the supertype of all types? Well, yes, but that's hardly a faithful description.

**Comment by timmyjose** [comment]
> but I assure you, `antype` is not ambiguous and is correct.

This is rather dismissive and rude. Also, from the very fact that this thread exists, evidence suggests that its intent and meaning are not as clear as you're implying.

**Comment by andrewrk** [comment]
Easy there, I can sense the passions in this thread escalating a bit. Let's all take a moment to remind ourselves that we have each others' best interests in mind, and try to keep the arguments focused on the technical bits. One thing to remember is that the ultimate decisions here will be based on the technical points made, and nothing else. If somebody makes a bad argument, I promise you I know it is a bad argument, you can just let it slide. Please, for my sake :sweat_smile:

**Comment by AssortedFantasy** [comment]
@EleanorNB @timmyjose I understand I might come off as a bit aggressive, Sorry about that and I'll try to be a bit more agreeable from now on if that makes for better debate.

I was trying to avoid the word "supertype" and "superclass" because its not really what I meant, it implies that it's somehow a different structure than a type itself, a higher level abstraction of sorts, but its not, it's just a union of types (which is still just a type).

Let's get away from shakey language and maybe I can show my same point again with pure mathematics, then I can show why I  personally believe `anytype` is a faithful and consistent name.

In mathematics, when you're being formal, you need to specify the domain (and codomain) of your functions when you define them.

For a function f(x,y) = ln(x)+y you'd need to specify something like x ∈ R+ and y ∈ R. I believe that Zig should try to match this.
Basically I think the little `:` is supposed to be an element of symbol.

So then `fn foo(x: u32, y: i32) i32`  means

`x` ∈ `u32` and `y` ∈ `i32`.

`anyerror` is a cool thing that's supposed to be the equivalent of a mathematical union of all errors. `anyframe` is supposed to be a union of all frames, and lastly `anytype` is supposed to be a union of all types.

Basically I don't believe

`fn bar(k : anytype)` is ambiguous, because a union of types makes perfect sense mathematically.

`k` ∈ `u0` ∪ `u1` ∪ ... ∪ `i0` ∪ `i1` ∪ ... ∪ `f64`  ∪ ...  ∪ `struct {a: i32, b:i32}` ∪ ...  `type`

The above is correct, k actually is any of those things. And it also shows why I don't like using `anyvalue`, In my opinion any value doesn't make sense because a type itself is just a union of values. So 2 is a value, an instance of a point struct is a value, but `k` is not an element of 2, and k is not an element of a instance of a point struct. 

I hope maybe this makes a bit more sense and is less angry sounding.

**Comment by marler8997** [comment]
I think the confusion here is caused by an inconsistency with the "any*" types.

`anytype` is not a type in and of itself.  It is a "placeholder" for other types.  Declaring an `anytype` parameter is what makes functions generic.  The word "any" in this case refers to the type itself meaning it can be substituted with "any type".

This is in contrast with `anyerror` and `anyframe` which are actual types and do not make functions generic.  They are union types which can hold "any value" from any error type or any frame type respectively.  Here the word "any" means a type that can represent "any value", whereas with `anytype`, "any" means the type is a generic placeholder that accepts "any type".

```Zig
const std = @import("std");

fn takeAnyError(x: anyerror) void {}
fn takeAnyFrame(x: anyframe) void {}
fn takeAnyType(x: anytype) void { }

pub fn main() void {
    std.debug.print("{}\n", .{&takeAnyError});
    std.debug.print("{}\n", .{&takeAnyFrame});
    // compile error because takeAnyType is generic
    //std.debug.print("{}", .{&takeAnyType});
}
```

At first glance, all 3 `takeAny*` functions appear as if they would behave similarly, but they are actually very different because only `takeAnyType` is generic.   Regardless of the actual names, I think using a different naming convention to distinguish between generic and non-generic behavior would be more clear.  Whether that means renaming `anyerror`/`anyframe` or `anytype` doesn't seem important but having a clear way to distinguish between them seems more so.

**Comment by EleanorNB** [comment]
That is a good point. Perhaps `vartype`? That communicates that the type is variable, and doesn't overload syntax.

**Comment by pixelherodev** [comment]
I like `vartype`, but type is *not* variable - it's *constant*, we just don't know *which*.

```zig
fn a(b: vartype) void {
    // @TypeOf(b) is *constant*, and will never change within a function permutation
}
```

**Comment by SpexGuy** [comment]
That's not correct, the type can change if the variable is not `const`.  This code is perfectly valid:
```zig
comptime {
    const Any = struct { value: anytype };
    var a = Any{ .value = "foo" };
    a.value = 4;
    a.value = Any{ .value = 3.0 };
}
```

**Comment by xackus** [comment]
I like `any`. It has precedent in TypeScript.

**Comment by gpanders** [comment]
I agree with what @SpexGuy said in his original comment:

> `any` might be a good choice except that it is a common enough variable or function name that the language probably shouldn't reserve it.

**Comment by pixelherodev** [comment]
How about `generic`, `arbitrary`, `value`, `anything`, etc?

**Comment by xackus** [comment]
> 
> 
> I agree with what @SpexGuy said in his original comment:
> 
> > `any` might be a good choice except that it is a common enough variable or function name that the language probably shouldn't reserve it.

In my experience `error` and `test` are much more common names than `any` when writing in languages that don't reserve them.
I think the benefit of having a (in my opinion) nicer keyword is far larger than the occasional inconvenience of choosing a different name.

**Comment by zzyxyzz** [comment]
How about `auto`?

**Comment by MasterOfTheTiger** [comment]
I was about to suggest autotype.

**Comment by pixelherodev** [comment]
I like autotype, I think it's the best option I've heard yet.

I might prefer `auto` over `autotype`, since it doesn't imply that the
value is of type type, but that might just be me.

**Comment by MasterOfTheTiger** [comment]
With `autotype` there would not be the same confusion as with `anyerror` and such, since it would be the only one using "auto". Thus it "automatically" determimes the type.

**Comment by SpexGuy** [comment]
C++ uses `auto` for type inference, where the type cannot change.  That might cause confusion for people learning the language, and I don't think it really conveys that the type can change.  The more I think about it, the more I like `any`.  It's such a generic word that I think it might be ok for the language to reserve, especially since variables or functions with that name can be trivially replaced by "hasAny".

**Comment by zzyxyzz** [comment]
> C++ uses auto for type inference, where the type cannot change. That might cause confusion for people learning the language, and I don't think it really conveys that the type can change.

@SpexGuy, you keep emphasizing this point, but I'm not sure I follow. The documentation only mentions `anytype` for generic function arguments, which surely must remain constant after being inferred in a particular invocation. Your above example with `anytype` struct fields is interesting, but I couldn't find any actual use of this in the Zig code base. Is this some kind of undocumented feature? Or even intended? I kind of struggle to imagine what a dynamic `Any` type would even mean in a language that does not use boxed values and runtime dispatch.

**Comment by alexnask** [comment]
@zzyxyzz 
`anytype` as a variable field is quite a useful feature in my opinion, when writing comptime code.  
The feature is undocumented but intended.  
When you use an `anytype` field the container type becomes comptime-only.  

Afaict atm this is only used in some `std.builtin.TypeInfo` structs (e.g. for default values of fields and sentinel values).  

However, it is also very useful for building up tuples.  
Here is an example from [ctregex](https://github.com/alexnask/ctregex.zig):

```zig
        // args is `anytype`, will be apssed to a std.fmt function
        // We intercept u21 unicode codepoint values and encode them as utf8 
        const ArgTuple = struct {
            tuple: anytype = .{},
        };
        var arg_list = ArgTuple{};
        for (args) |arg| {
            if (@TypeOf(arg) == ?u21) {
                if (arg) |cp| {
                    arg_list.tuple = arg_list.tuple ++ .{ctUtf8EncodeChar(cp)};
                } else {
                    arg_list.tuple = arg_list.tuple ++ .{"null"};
                }
            } else if (@TypeOf(arg) == u21) {
                arg_list.tuple = arg_list.tuple ++ .{ctUtf8EncodeChar(arg)};
            } else {
                arg_list.tuple = arg_list.tuple ++ .{arg};
            }
        }
```

**Comment by SpexGuy** [comment]
> I kind of struggle to imagine what a dynamic Any type would even mean in a language that does not use boxed values and runtime dispatch.

The type of an `anytype` cannot change at runtime.  But comptime zig is an interpreted language with boxed values and type values and dynamic dispatch and everything, so the type of a variable stored in `anytype` changing at comptime makes just as much sense as the type of a `var` changing in JS.  It's currently restricted to function parameters and struct members, but it could easily be extended to be allowed as the given type of a local `comptime var` in the future.  I'm hoping this happens, because the `Any` struct workaround gives all the same functionality but is just more typing.

`anytype` fields are currently used by `std.builtin.TypeInfo.Pointer` to represent the sentinel. In order to robustly construct the type `*<modifiers>[1]T` from `*<modifiers>T`, for example, modifiers on the pointer need to be preserved. The maintainable approach is to use `@typeInfo` to get a type info for the pointer and modifiers, alter the target type of the pointer, and then use `@Type` to construct the altered type. But in order to do this, the type of the sentinel field must also change from `@as(?T, null)` to `@as(?[1]T, null)`.  That requires a struct member that can change types at comptime, so this behavior probably isn't going away.

**Comment by zzyxyzz** [comment]
@alexnask, @SpexGuy 
Thanks for the explanations. Makes sense.

I would actually argue that this makes the two uses of `anytype` quite distinct: One for creating generic functions and one for representing comptime mutable types. That both use the same keyword is economical, but confusing. Maybe the two uses should simply be split, with `auto` indicating a generic parameter and `any` or `anyval` or whatever standing for a comptime dynamic type. Of course that would reserve two short keywords...

**Comment by kenaryn** [comment]
I propose _anyitem_ as it is in English language more holistic than _object._ It conveys the idea of a very generic concept like an idea, a person, a place or even a physical or conceptual object.

As for me, _anyitem_ may be adequate to express any logical concept as abstact as a value of a value.

**Comment by Mouvedia** [comment]
If I understand correctly, [from what Iv read](https://github.com/ziglang/zig/issues/4820#issuecomment-604608183) in #4820, the crux of the problem was to convey the notion of singularity, hence plain `any` was rejected on that basis.

`anytype` will collapse to a _single_ type on/for function calls and struct instantiations. That's the _moment_ we chose to describe the name given to the type. It seems to me, that is where the confusion lies. Some of us want to encompass it, and cover what precede the collapse.

If we keep that notion of singularity then we can more easily come up with a proper name for it.
I like `any` but it's too ambiguous. Something like `infer`, `inferredType`, `auto` or `autoType` would convey what we were trying to achieve with the initial rename much more clearly.

**Comment by Rocknest** [comment]
Anytype looks a bit misleading to me. Lets look if the type system is consistent:
- `anyerror`, variable/parameter compatible with all error values.
- `anyframe`, var/param compatible with all frame pointers. 
- `type`, var/param compatible with all types. Requires `comptime`. One of the earliest types. Sometimes its inconvenient that `type` is a keyword.
- `anytype`, its a type/keyword(??) that infers a type of a value.
```zig
@TypeOf(anytype);
//error: expected token ')', found 'anytype'
```

Lets see what TypeOf will produce:
```zig
pub fn abc(a: anyerror, b: anyframe, comptime c: type, d: anytype) void {
  @compileLog(@TypeOf(a), @TypeOf(b), @TypeOf(c), @TypeOf(d));
}
comptime { 
  abc(undefined, undefined, i32, @as(i32, 5));
}
```
`| anyerror, anyframe, type, i32`
`<source>:2:3: error: found compile log statement`

As you can see that symmetry does not hold. I believe that this type/keyword should not be prefixed with `any`. The type of types may be renamed to `anytype`, that would allow to create fields and variables named `type` using the simple syntax.

**Comment by RaphiJS6-13** [comment]
What about `expr` or `expression`?

**Comment by RaphiJS6-13** [comment]
> > I kind of struggle to imagine what a dynamic Any type would even mean in a language that does not use boxed values and runtime dispatch.
> 
> The type of an `anytype` cannot change at runtime. But comptime zig is an interpreted language with boxed values and type values and dynamic dispatch and everything, so the type of a variable stored in `anytype` changing at comptime makes just as much sense as the type of a `var` changing in JS. It's currently restricted to function parameters and struct members, but it could easily be extended to be allowed as the given type of a local `comptime var` in the future. I'm hoping this happens, because the `Any` struct workaround gives all the same functionality but is just more typing.
> 
> `anytype` fields are currently used by `std.builtin.TypeInfo.Pointer` to represent the sentinel. In order to robustly construct the type `*<modifiers>[1]T` from `*<modifiers>T`, for example, modifiers on the pointer need to be preserved. The maintainable approach is to use `@typeInfo` to get a type info for the pointer and modifiers, alter the target type of the pointer, and then use `@Type` to construct the altered type. But in order to do this, the type of the sentinel field must also change from `@as(?T, null)` to `@as(?[1]T, null)`. That requires a struct member that can change types at comptime, so this behavior probably isn't going away.

There's a workaround for the `anytype` restriction that mentioned:

```zig
const Any = @typeInfo(struct { a: anytype }).Struct.fields[0].field_type;
```

**Comment by vkcz** [comment]
I'm in favor of (should this be changed) `anything`: it's consistent with `any...` type-category names, and coincides with a nicely relevant existing English word, but doesn't give any suggestion that the value is related to the `type` type.

**Comment by marler8997** [comment]
A couple more ideas I thought of after reading people's comments:

* `defer` or `deferred`: rather than declaring a type, the function is choosing to "defer" that responsibility to something else

```zig
fn foo(x : defer) {
}
```

* `placeholder`: instead of declaring the type, the function is creating a placeholder for a type to be filled in by something else

```zig
fn foo(x: placeholder) {
}
```

**Comment by pixelherodev** [comment]
I would avoid defer, since it's already used for deferred execution.

**Comment by zzyxyzz** [comment]
Since we are discussing *generic* function arguments, why not just say so:

```zig
fn foo(x: generic, y: @TypeOf(x)) {
    ...
}
```

I think this was already suggested by @pixelherodev, but didn't gain traction.

`generic` also seems like a fair description of the other use-case mentioned in the thread -- comptime-typed struct fields and variables:

```zig
const ArgTuple = struct {
    tuple: generic = .{},
}
// ... See @alexnask's comment above for rest of example.
```

**Comment by MasterQ32** [comment]
If we're actually going to change it, I am strongly for `generic` as this is self-explanatory and explains what it does

**Comment by cryptocode** [comment]
Yeah I really like the suggestions from @zzyxyzz and @marler8997, `generic` and `placeholder`. They stand out appropriately and describes the idea very well.

**Comment by mikdusan** [comment]
<img width="133" alt="image" src="https://user-images.githubusercontent.com/48141240/105994999-5eee1200-6076-11eb-8198-f0fc1de33b77.png">

My vote: first choice `any`, second `anyval`

**Comment by Mouvedia** [comment]
I agree with @vkcz, `anything` works:
```
anyframe
anyerror
anything
```

But I would be fine with [`anyexpr`/`anyexpression`](https://github.com/ziglang/zig/issues/5893#issuecomment-751420413) or `anyval`/`anyvalue` **if** the terms expression or value are more idiomatic in zig.

**Comment by zzyxyzz** [comment]
Because I currently have important work to procrastinate on, I have carefully read through the entire thread and attempted a summary. My conclusion is that `anytype` is actually not too bad, but if we do decide to change it, then we should go for something that specifically emphasizes the generic instantiation behavior, such as `auto`, `infer` or `generic`. For the reasoning behind this conclusion, read on.

## Prelude

I'd like to draw attention to the fact that `anytype` has two quite distinct uses:

1. Generic functions with inferred argument type. This is the main use case.
2. Comptime dynamic struct fields. Since `comptime` implements semantics resembling a dynamic scripting language, a struct field declared as `anytype` can change its type during comptime execution. This can be used, for example, to build up tuples programmatically. In the future, comptime dynamic variables might be allowed too. While not unimportant, this use case is both advanced and rare.

From a certain technical perspective, the two cases can be regarded as two sides of the same coin: Both have dynamic variables with the type inferred from the supplied value. In that view, the inferred type of a generic function argument is actually dynamic, and acquires its constness only as a side effect of function arguments being constant in Zig. While technically correct, I find this view mostly unproductive. In practice, the difference between the two use cases is almost as big as the difference between languages with static and dynamic typing. At least in my head, they occupy quite distinct mental niches, although I can't vouch for the heads of other developers.

Because of this, using the same keyword in both cases will always feel kind of unsatisfactory. The semantics of either one or the other will be described poorly. One way out of this would be to simply use different keywords, but for reasons of keyword economy and the fact that the two are indeed somewhat related, I would say this is overkill. However, the inherent conflict between the two uses should be acknoledged and preferably resolved in favor of generic functions. This case is not only much more common, but also much more likely to be encountered by newcomers, so descriptiveness and clarity are important here. I would find it acceptable if the much more expert-level case of dynamic comptime fields suffers a bit of poor aesthetics in return.

## Type Theory

With that out of the way, let's dig in. For the original motivation of this issue, I'll quote @SpexGuy:

> The value of a variable of type anyerror is some error.
> The value of a variable of type anyframe is some frame.
> The value of a variable of type anytype is usually not a type.

> Said another way,
> A variable that holds some unknown error is an anyerror.
> A variable that holds some unknown frame is an anyframe.
> A variable that holds some unknown type is a type.
> A variable that holds some unknown value is an anytype?

As pointed out by @AssortedFantasy, there seems to be a subtle error of reasoning in that last line. "A variable that holds some unknown value" doesn't actually say anything. It is the purpose of variables to hold unknown values. Of course, the *range* of these values may be constrained by the type of the variable to various extents:
* A variable typed with a specific enum or errorset can only hold a handful of different values.
* A variable typed with `anyerror` can hold any value from the union of all errorsets in the program.
* A variable typed with `anytype` can hold an integer, a float, an error, an enum, or anything else, because `anytype` is the union of all types. In PL theory it would be called top, or root of the type hierarchy.

In short, `anytype` is actually the appropriate term to describe the type of a variable that may hold anything. `any` would do equally well.

## Generics

Despite this, I'm actually in favor of changing it to something else. The above reasoning is more appropriate to case (2) mentioned in the prelude, that is, actual dynamically typed variables. But as argued before, case (1) is more important and `anytype` (and especially `any`) strongly suggests that you are dealing with a variable with unconstrained range. Instead, what happens is that you get a variable of a very specific and constant type in a separate function instantiation. This was pointed out by @marler8997: neither `anyerror` nor `anyframe` instantiate new functions, but `anytype` does.

For the above reasons, I think that all `anyX` proposals are actually solving the wrong problem. It is the `any` in `anytype` that we should take issue with, not the `type`. This would rule out `anyitem`, `anything`, `anyval`, `anyvalue`. In my opinion, all of these are strictly inferior to `anytype` or `any`.

The proposals that I would recommend for consideration are those that express the generic function instantiation semantics directly. These include, in order of my personal preference, `auto`, `infer`and `generic`. I'm less fond of `autotype`, and `defer` and `defertype` I find positively confusing in this context.

To whom it may concern: Thanks for reading!

**Comment by zzyxyzz** [comment]
## Addendum

Though I personally don't have an issue with this, it can be argued that `type` in `anytype` is
1. redundant, because it being a type is already implied by its location on the right of the colon.
2. misleading, because Zig can have values of type `type`, which may suggest that `anytype` constrains the variable to holding `type` values of any kind.

Both of this is true, but the only correct solution in that case is `any`, which is in fact what most 
languages use to describe variables that can hold values of all types. Going for `anyvalue` or `anyitem` would be even even more redundant an misleading.

With that said, I think the difference between `anytype` and `any` is not that dramatic, and probably not worth changing. If we seriously contemplate a change, it should favor the "generics" interpretation, as argued in my above comment.

**Comment by Rocknest** [comment]
There is a universal 'don't care' syntax in zig - the underscore. 
```zig
fn foo(x: _) void {
    // i don't care what the type is, just give me the value. 
}
```

**Comment by haze** [comment]
maybe we could use `bruh` with a similar sentiment as `usingnamespace`

```rust
fn foo(x: <bruh>) void {
    // i don't care what the type is, just give me the value. 
}
```

**Comment by mikdusan** [comment]
it's emoticon time `(_:_)`

**Comment by CoolRustacean** [comment]
> A couple more ideas I thought of after reading people's comments:
> 
> * `defer` or `deferred`: rather than declaring a type, the function is choosing to "defer" that responsibility to something else
> 
> ```zig
> fn foo(x : defer) void {
> }
> ```

In that case...

```Zig
if (defer == defer) {
    defer _ = defer;
} else defer switch (defer) {
    else => defer == defer
};
```

**Comment by Mouvedia** [comment]
After reading the comments a second time, I am leaning towards 2 proposals:

- [`_`](https://github.com/ziglang/zig/issues/5893#issuecomment-769027502)
- [`any` and `auto`](https://github.com/ziglang/zig/issues/5893#issuecomment-663205382)

Personally I _still_ like `anything` because it's consistent with the existing `anyerror` and `anyframe` and the upcoming [`anyopaque`](https://github.com/ziglang/zig/issues/323).

**Comment by Zooce** [comment]
_Disclaimer: I'm rather new to this language -- been watching it for a while but haven't yet put it into much practice, until now. So I figured that maybe a newcomer's perspective might be useful here...maybe not...?_

Today I was trying to learn the difference between `x: anytype` and `comptime T: type, x: T` and the nice folks over at [zigforum.org](https://zigforum.org/t/why-anytype-and-type/217) helped get me through it.

I read the comments in this issue in their entirety, and there are some great ideas here. My takeaway is that `anytype`, although not necessarily incorrect, is somewhat inconsistent with the other `any*` keywords. As a newcomer to the language, I think it would be much easier to understand `anytype` if it were changed to something more indicative of its **generics** use case. The `auto` and `generic` suggestions are my favorite.

Also, `anytype` **does** make sense to me in the compile time use case (i.e. as a dynamic type).

I did have one (potentially crappy) solution -- just getting the idea out there. Since we can essentially accomplish the generic behavior of `x: anytype` with `comptime T: type, x: T`, maybe one way to deal with this is to remove `anytype` as a function parameter, and just keep it as a struct field type (so we still have the dynamic type behavior at compile time). One argument in favor of this would be that the builtins use the `comptime T: type, x: T` pattern already, so there's a consistency there. _Just an idea..._

**Comment by marler8997** [comment]
@Zooce, yes I've also found that `anytype` is inconsistent with the other `any*` keywords which can cause some confusion.  I agree that changing it to something like `auto` or `generic` would be an improvement.

As far as I can tell, there's very little difference between `x: anytype` and `comptime T: type, x: T` besides ergonomics for the caller.  I believe the caller can emulate the behavior of either one:

```zig
fn exampleAnytype(x: anytype)
fn exampleComptimeT(comptime T: type, x: T)

// emulate ComptimeT when calling a function that takes Anytype
exampleAnytype(@as(T, x))

// emulate Anytype when calling a function that takes ComptimeT
exampleComptimeT(@TypeOf(x), x)
```

In practice, there seems to be a number of factors that determine which one someone would choose.  Accepting anytype can make it more convenient to call the function.  If the function only accepts slice types, then declaring the signature as `comptime T: type, x: []T` helps clarify what the function accepts more than `x: anytype` would.

In my opinion it's not clear when to use which kind of signature, which doesn't jive with one of Zig's zen points "Only one obvious way to do things".  I created an issue a couple years ago to discuss when the standard library should use one signature type over the other here: https://github.com/ziglang/zig/issues/2904

**Comment by Zooce** [comment]
Those are good points (one way to do things and ergonomics). Personally, I would tend to favor the "only one way to do things" philosophy, but ergonomics (and also readability) are certainly important. Here's a bad example that ruins ergonomics (at least for me):
```
fn testMe(comptime OutType: type, comptime InType: type, x: InType) OutType {
    if (OutType == bool) {
        return x > 0;
    } else {
        return if (x > 0) 1 else 0;
    }
}

test "bad example" {
    const x: i32 = 5;
    const u = testMe(u64, i32, x);
    const b = testMe(bool, i32, x);

    //...do some `expect`s
}
```
From the call site, having more than one `type` anywhere in the function parameters, it's not at all clear to the reader what's going on. Maybe if Zig had parameter labels it would work...but still not great. Using `anytype` for `x` in this case is obviously better.

**Comment by MasterQ32** [comment]
@marler8997 `anytype` arguments aren't completly interchangible with `comptime T: type, x: T`:
```zig
fn takesAnytype(value: anytype) void { ... }

test {
    takesAnytype(.{}); // this is different from @TypeOf(.{}), .{}
}
```

**Comment by YohananDiamond** [comment]
An idea I've had recently is to use a prefix on the function argument (instead of putting it as the type). Let's use `generic` as an example for this.
Instead of `fn max(comptime T: type, a: T, b: T) T {` we'd have:
```zig
fn max(generic a, b: @TypeOf(a)) @TypeOf(a) {
    return if (a > b) a else b;
}
```
To be fair, though, I think it's kind of ambiguous - it's hard to understand whether the `generic` applies to just `a` or `a` and `b` (same for the type, `@TypeOf(a)`), and would cause conflicts with https://github.com/ziglang/zig/issues/5519 if it's ever proposed. Maybe something like:
```zig
fn max(generic a: _, b: @TypeOf(a)) @TypeOf(a) {
    return if (a > b) a else b;
}
```
Maybe I'm opening another path to the name bikeshedding with the `_` but what I mean here is that placing a keyword before the argument name emphasizes that `anytype` (or `generic`, or whatever) is not a type in itself, and just indicates that the parameter (or field) is not concrete.

Also, this would work normally for structs too:
```zig
const OldS = struct {
    x: anytype,
};

const NewS = struct {
    generic x: _,
};
```

For last, although I don't think it would be very consistent, we could also do something like:
```zig
fn max(generic a: T, b: T) T {
    return if (a > b) a else b;
}
```
Basically, `T` is being declared at `generic a: T`, and it can be used throughout the function declaration (and possibly inside its scope). It's similar to `a: $T` from Jai and Odin.
The downside with this is that it's not clear that `T` is being declared here, so it could cause some confusion.

**Comment by InKryption** [comment]
> ```zig
> fn max(generic a: _, b: @TypeOf(a)) @TypeOf(a) {
>     return if (a > b) a else b;
> }
> ```
I actually really like this train of thought, but I think it would be much improved by more explicit syntax. Instead of implicitly declaring that a type argument is to be instantiated through the declaration of a normal parameter, it could be neater to have some sort of syntactic sugar, imitating what we already have, something like:
```zig
fn max(generic T: type, a: T, b: T) T {
    return if (a > b) a else b;
}
```
where "max" can then be called as:
```zig
_ = max(3, 2)
```
Here, you could replace "generic" with whatever flavor keyword you want, but you get the idea. It makes it explicitly clear that we are dealing with some syntactic sugar that allows us to infer the type of a parameter at the call-site, like our current "anytype", while also unifying the way we write comptime T and generic functions. Also has the benefit of having an explicit type parameter, instead of having to declare ´comptime T = @TypeOf(x)´ inside the function.

First time posting anything, but thought I'd throw my two cents in as a newcomer. I'm sure there's some key issue that I'm missing, so apologies if I'm just making noise.

**Comment by windows-h8r** [comment]
@AssortedFantasy 
> Personally, I believe a type definition answers the question "What type is this?".

No. Types describe values, not themselves.
> `e: anyvalue` -> The type of `e` is any value [ of any type?]

This should be read as...
`e: anyvalue` -> `e` can hold any value.
`e: anyframe` -> `e` can hold any frame.
`e: anyerror` -> `e` can hold any error.
> c: anytype -> The type of c is any type.

Your reasoning actually makes the opposite point. The name `anytype` describes itself. If it was called `typeany`, I would agree with you that `any` describes the type rather than the value.

**Comment by lemaitre** [comment]
> I actually really like this train of thought, but I think it would be much improved by more explicit syntax. Instead of implicitly declaring that a type argument is to be instantiated through the declaration of a normal parameter, it could be neater to have some sort of syntactic sugar, imitating what we already have, something like:
> 
> ```zig
> fn max(generic T: type, a: T, b: T) T {
>     return if (a > b) a else b;
> }
> ```

This looks like C++ templates, when the function parameters are split in 2:
- Deducing parameters
- Explicit parameters

In that case, the keyword should probably be `deduce`:

```zig
fn max(deduce T: type, a: T, b: T) T {
  return if (a > b) a else b;
}

const a = max(1, 2);
```

This opens many possibilities, like deducing ints:

```zig
fn array_max(deduce T: type, deduce N: u16, arr: [N]T) T {
  // ...
}
```

But this would also lead to much more complex designs (both user code and compilers).

**Comment by InKryption** [comment]
> This opens many possibilities, like deducing ints:
> 
> ```zig
> fn array_max(deduce T: type, deduce N: u16, arr: [N]T) T {
>   // ...
> }
> ```
> 
> But this would also lead to much more complex designs (both user code and compilers).
Would it though?

**Comment by lemaitre** [comment]
> I don't think it leads to much more complex designs that the aforementioned `a: generic T`-esc syntax, since all it's doing is moving the definition of T outside of the parameter declaration.

Compiler-wise, it is definitely more complex as this syntax would need to be able to deduce from multiple arguments:

```zig
fn max(deduce T: type, a: T, b: T) T {
  return if (a > b) a else b;
}
```

What should the compiler do if `a` and `b` are different types? coerce into single type? error?

**Comment by windows-h8r** [comment]
> > This opens many possibilities, like deducing ints:
> > ```zig
> > fn array_max(deduce T: type, deduce N: u16, arr: [N]T) T {
> >   // ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But this would also lead to much more complex designs (both user code and compilers).
> 
> Would it though? People seem to be somewhat in favor of stricter type checking than the current compile-time duck-typing. I don't think it leads to much more complex designs that the aforementioned `a: generic T`-esc syntax, since all it's doing is moving the definition of T outside of the parameter declaration.
> I like the deduce keyword better, now that you mention it.

I have an idea. If we add support for default parameters, and make default parameters go first, we can do something like this:

```zig
const std = @import("std");

fn square(comptime T: type = any, n: T) T {
    return n * n;
}

fn main() void {
    const x: u32 = 5;
    std.debug.print(
         "{} = {}\n",
         square(u32, x),
         square(x)
    );
}
```

**Comment by InKryption** [comment]
> Compiler-wise, it is definitely more complex as this syntax would need to be able to deduce from multiple arguments:
> 
> ```zig
> fn max(deduce T: type, a: T, b: T) T {
>   return if (a > b) a else b;
> }
> ```
> 
> What should the compiler do if `a` and `b` are different types? coerce into single type? error?

I mean, this would pretty clearly be an error for them to be different types, seeing as this should be no different to b being declared with type `@TypeOf(a)`, and then declaring `const T = @typeOf(a)`, T is just being given a name earlier on. At least that is what I would imagine. Perhaps I am missing some intrinsic flaw with how this works at a compiler level; if so I apologize and concede. But do enlighten me.

**Comment by windows-h8r** [comment]
@InKryption 
There still needs to be type coercion. If 

> I agree with @vkcz, `anything` works:
> 
> ```
> anyframe
> anyerror
> anything
> ```
> 
> But if the terms expression or value are more idiomatic in zig I would be fine with [`anyexpr`/`anyexpression`](https://github.com/ziglang/zig/issues/5893#issuecomment-751420413) or `anyval`/`anyvalue`.

Not `anyexpr` because it's virtually unpronounceable.

"e•nē•ex•pre•shin"?
"e•nē•ex•pur"?
"e•nē•ex•pehr"?

**Comment by ifreund** [comment]
I'd like to propose renaming the `anytype` keyword to `ducktype`. Unlike `anyerror`, `anyframe`, and `anyopaque` which are all primitive types, `anytype` is a keyword and I think we should drop the "any" prefix to avoid confusion. I also think that `ducktype` describes the semantics much more accurately and is a fairly well known concept in programming: https://en.wikipedia.org/wiki/Duck_typing

**Comment by amfogor** [comment]
```
fn waitWhat(comptime _ : type, comptime _ : anytype) void
{
}
```
I think, if you show this to a newcomer, they will likely find it confusing.
I also found very confusing almost all the suggested solutions.

I propose to rename `type` to `anytype` and `anytype` to `anyvalue`.
Thus the example becoming
```
fn foo(comptime _ : anytype, comptime _ : anyvalue) void
{
}
```
I imagine a newcomer would need no explanation as to what each keyword means.
It's simple and feels right. But maybe that's just me.

**Comment by tauoverpi** [comment]
@amfogor `type` is a valid type that has the type `type` along with being the type of all types so I'd argue that changing it's name obscures more than it clarifies. It's also consistent with other languages which can work with types as values (Idris, Agda, etc).

**Comment by locriacyber** [comment]
Every term has a type, so `a_type`?

**Comment by batiati** [comment]
What if, instead of `fn foo(a: anytype) void` we did `fn foo(a: @TypeOf(a)) void`
Being `a: @TypeOf(a)` not a recursive dependence, but the exact equivalent of `anytype`.

- It would settle de discussion about `anytype` inconsistent name
- `@TypeOf(...)` is clear enough to express generics.
- It would allow more advanced use cases, such as:

```zig
// Parameter order
fn foo(a: @TypeOf(b), b: @TypeOf(b)) void { 
}

// In-place contract validations
fn foo(a: ValidateContract(@TypeOf(a))) void { 
}

fn ValidateContract(contract: type) type {
    // some meta validation here
    return contract;
}

// Type transformations
fn foo(a: TransformType(@TypeOf(a))) void { 
}

fn TransformType(arg_type: type) type {
    if (arg_type == comptime_int) {
        return i64;
    } else {
        return arg_type;
    }
}
```

**Comment by nektro** [comment]
i like #9260 as a solution to this

**Comment by zzyxyzz** [comment]
@batiati
There was already a proposal for this idea (#6615). It has been rejected on the grounds that it doesn't really add anything that can't be done with the status quo. But now that anytype *fields* are gone from the language, this may allow us to remove `anytype` completely, which may just tip the balance for this feature. I don't know.

**Comment by jibal** [comment]
> `any` might be a good choice except that it is a common enough variable or function name that the language probably shouldn't reserve it. `infer` was suggested previously, but doesn't convey that the type can change over the variable's lifetime. Maybe `anyvalue`, `anyval`, or `vartype` would be better?

How about simply `anything`?

**Comment by ityonemo** [comment]
A bit more work, but why not just:

```
fn my_function(foo: _, bar: u8) void {
}
```

**Comment by jibal** [comment]
Because `_` is something ignored or not cared about, but that's not what `anytype` means ... it means that the parameter is generic. (So `generic` is a possibility.)

**Comment by leecannon** [comment]
In array's it mean's infer the length `const arr = [_]u8{1,2,3};`

**Comment by Gaai** [comment]
My brainstorm came up with:
alltype
flextype
flexy
mocktype
mock
supertype
Take it, or leave it. Not saying it's super brilliant. I liked suggested any and ducktype.

**Comment by cryptocode** [comment]
> A variable that holds some **unknown** value is an anytype?

Maybe there's a clue there? I like the terminology of the typesafe parts of TypeScript where 

* *unknown* is the typesafe _top type_ which can take any value, and 
* *never* is the _bottom type_ which can take no value

The renaming would be:

```
    anytype  -> unknown
    noreturn -> never
```

Example:

```zig
pub fn get(x: unknown) @TypeOf(x) {
    ...
}

pub fn exit() never {
    ...
}
```

(_never_ and _nothing_ are used in a bunch of languages as the bottom type)

**Comment by deflock** [comment]
After getting some more Zig-experience `anytype` just blows my mind. So inconsistent.

If this cannot be solved by eliminating it and we're choosing a new name then my ordered preferences:
* `fn (x: anything)`
* `fn (x: generic)`
* `fn (x: any)` - only on 3rd place because of TypeScript's `any` influence on newcomers where it's considered as a bad-practice
* `fn (x: whatever)` 🤣

**Comment by nacho00112** [comment]
`vary`?
```zig
fn myFunction(x: vary) {}
```

**Comment by jibal** [comment]
> @AssortedFantasy
> 
> > Personally, I believe a type definition answers the question "What type is this?".
> 
> No. Types should describe values, not themselves.
> 
> > `e: anyvalue` -> The type of `e` is any value [ of any type?]
> 
> This should be read as... `e: anyvalue` -> `e` can hold any value. `e: anyframe` -> `e` can hold any frame. `e: anyerror` -> `e` can hold any error.

Indeed, this cuts to the heart of it. It is clear that AssortedFantasay's reasoning, despite the time he spent on it, his assurances that it is correct, and the 29 upvotes it received, is in fact _not_ correct, from the fact that we have `anyerror` and `anyframe`, not `anyerrortype` and `anyframetype` (nor, of course do we have `u32type` etc.)  `x: foo` means that `x` is a `foo`. `x: anyerror` means that `x` is any error, or `x` is any _sort_ of error, not that `x` is any _type_ of error, because `x` is not a type at all. (The type of `x` is any type of error, but as you correctly point out, type designators give the type of the variable, not the type of the type designator.) Likewise `x: anyframe` means that `x` is any _sort_ of frame (its type is any frame type, but a type designator describes the variable, not itself), and `x: anything` should mean that `x` is any _sort_ of thing (its type is any type, but a type designator describes the variable, not itself). Again, in `x: foo`, `foo` is x's type, and `x`'s type should only have the word "type" in it is `x` is a type. Thus, `anytype` is wrong.

**Comment by nacho00112** [comment]
`anyarg`?
```zig
fn myFunction(x: anyarg, y: anyarg) anyarg {}
```

**Comment by mlugg** [comment]
Please let's not just flood this issue with drive-by keyword suggestions which just vaguely match the idea. If you have a suggestion, justify why you consider it an improvement on status quo, and why it fits with Zig's existing keywords and types. Also note that, as always, your opinion will have a lot more weight if you have _demonstrable practical experience_ using Zig.

**Comment by nacho00112** [comment]
I agree with you.
But the `vary` one has its reason, the old name of anytype was var.
about `unset`, it think it has potential to be a keyword, beyond that, a keyword that may be reused for another thing.
I don't like `anything`, because remember that what anytype is supposed to do is to
to allow the value to be of any type, not anything,
that it is anything is not more than a side effect,
so technically I think the correct name would be something like ofanytype, this way it would be less confusing
but that's ugly, at this point, I suggest to find a prettier way of saying that

**Comment by jibal** [comment]
> remember that what anytype is supposed to do is to allow the value to be of any type, not to be anything,

To repeat my previous comment: a type designator describes the thing it's the type of, not itself. In `x: anything`, `x` can be anything, not any type.

**Comment by nacho00112** [comment]
forget the anyarg one, it was a quick one and it doesn't even make so much sense so I edited it.
I've said myself that ofanytype is ugly, it was only so you can get the idea.
`unset` purpose is to be more like a keyword, and as a keyword, I believe it sounds good.
`vary` is based on the old name, what I'm trying is to do is to replicate it, I don't know if `var` was considered a bad one.
my point is that I think that saying that it's of any type describe better what the keyword do
than saying it can be anything, both ways describe the value as you say

**Comment by terraquad** [comment]
If `anytype` gets changed to something else, maybe we could also rename `type` to `anytype` because I think "type" is a common variable name (at least for me).

**Comment by InKryption** [comment]
You can already use `type` as a field name.

**Comment by paperdev-code** [comment]
Not a terribly original suggestion but just because I haven't seen it described here yet.

If inferred error sets are defined by not specifying the error set, maybe inferred parameters can be defined by... not specifying the type ;P

```zig
fn genericFn(some_value) !void { ... }

// not exactly a new pattern either:
const std = @import("std");
var something = 5;
```

It's explicit in that you are taking in some parameter of some _value_, just not of any explicit type.

In cases where a type is required, usually giving it as a parameter is already less clunky the `@TypeOf` approach.
```zig
fn add(T: type, x : T, y : T) T { ... } // always preferable in such cases because we want type equivalence
fn updateEntity(T: type, entity: T) void { ... } // bit more clunky, and we don't need it if we intend to duck type.
```

**Comment by xdBronch** [comment]
how would you express that in function types?

**Comment by paperdev-code** [comment]
> how would you express that in function types?

Good point

**Comment by pranavsetpal** [comment]
I'll preface my suggestion with the fact that I barely use Zig, just follow its development, and I apologize if my suggestion is not good.

From what I have read, `anytype` does not say the variable cannot be of any type, so string at one moment but a number at another, but rather any **particular** type, i.e. the type is fixed once it is decided.

Usually, in mathematical proofs, when we want an arbitrary constant value, we say "Let x be some value in S (where S is some set)". That is, we use the word `some`. Perhaps that may a better word to use here.

So in essense, replace `anytype` with `sometype`

**Comment by amarz45** [comment]
> So in essense, replace `anytype` with `sometype`

That doesn't solve the issue because the type `sometype` would represent some value, not some type.

**Comment by intender1** [comment]
What is the policy for adjective words like `autotyped`?

**Comment by fidelicura** [comment]
After reading all the comments, I think `anytype` should stay. The `any*` naming pattern is actually consistent - `anyerror`, `anyframe`, and `anytype` all represent typed values, not the types/categories themselves. For actual type values, Zig already has the `type` keyword.

Alternatives like `anyvalue` would actually break this reasoning, since 'value of any value' doesn't make sense - it would be redundant naming that doesn't follow the pattern where `any*` describes what **kind of value** it holds.
