### ISSUE TITLE
LLVM 12 stack traces test regression: ReleaseSafe no longer has line number information

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#8421]
With LLVM12rc4 this test case is failing:

```
Test 2/14 stack-trace return (ReleaseSafe)...
========= Expected this output: =========
error: TheSkyIsFalling
source.zig:4:5: [address] in std.start.posixCallMainAndExit (test)
    return error.TheSkyIsFalling;
    ^

================================================
error: TheSkyIsFalling
???:?:?: 0x2034b9 in std.start.posixCallMainAndExit (test)
```

Unclear why. Did LLVM's debug info get worse? Is it something fixable upstream? Can we improve debug info handling on our end? More investigation is needed.

**Comment by LemonBoy** [comment]
> Unclear why

The fact it even worked up to this point is surprising, the naive stack walker we use to collect the frame addresses cannot work whenever the frame pointer is disabled and if it does work it's just out of sheer luck.
On modern architectures (aka not register-starved, I'm looking at you x86) having one less register is not a big deal in terms of performance, we may force-enable it in release (safe?) mode to have a fast way of collecting a stack trace (that's what Apple does for its mobile devices).

**Comment by mikdusan** [comment]
yet another difference in llvm12 ReleaseSafe optimizer disposition on different platforms? -- macos/llvm12 does not manifest this issue

**Comment by mikdusan** [comment]
freebsd manifests this issue as well, so looks like contained to targets using ELF

**Comment by mikdusan** [comment]
- s1.zig
```zig
fn foo() !void {
    return error.TheSkyIsFalling;
}

pub fn main() !void {
    try foo();
}
```

What follows is `llvm-dwarfdump` on exe from `zig build-exe s1.zig` showing `DW_TAG_compile_unit`:
- look to `DW_AT_ranges`
- in all output **EXCEPT** llvm12+ReleaseSafe, the ranges are in order
- it seems our `dwarf.zig` assumes order and supplies the **first** range lower-addr; if that is not lowest of all ranges it borks `LineNumberProgram` -- undefined values are then evaluated and we just luck out that 64-bit `0xaaaaa....` is obscenely large and produces failure instead of false-positives
- unsure why llvm12 emits more ranges but ReleaseFast and ReleaseSmall are shorter and ordered, consistent with debug executable
- unknown if that's illegal or we just got lucky with ordered ranges up until now
- grain of salt: out of my element here, just a pattern I've noticed

---

- llvm11
```
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("zig 0.0.8")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name    ("s1")
              DW_AT_stmt_list   (0x00000000)
              DW_AT_comp_dir    (".")
              DW_AT_GNU_pubnames    (true)
              DW_AT_low_pc  (0x0000000000000000)
              DW_AT_ranges  (0x00002a60
                 [0x00000000002042e0, 0x00000000002063d3)
                 [0x0000000000206430, 0x000000000020cc2f)
                 [0x000000000020ccd0, 0x0000000000239d4d))
```

- llvm11, -OReleaseSafe
```
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("zig 0.0.8")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name    ("s1")
              DW_AT_stmt_list   (0x00000000)
              DW_AT_comp_dir    (".")
              DW_AT_GNU_pubnames    (true)
              DW_AT_low_pc  (0x0000000000000000)
              DW_AT_ranges  (0x0000bc30
                 [0x00000000002030b0, 0x00000000002044c8)
                 [0x0000000000204500, 0x000000000020a428)
                 [0x000000000020a4a0, 0x0000000000214645))
```

- llvm12
```
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("zig 0.0.8")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name    ("s1")
              DW_AT_stmt_list   (0x00000000)
              DW_AT_comp_dir    (".")
              DW_AT_GNU_pubnames    (true)
              DW_AT_low_pc  (0x0000000000000000)
              DW_AT_ranges  (0x00002ee0
                 [0x0000000000204c20, 0x0000000000206b58)
                 [0x0000000000206bb0, 0x000000000020d172)
                 [0x000000000020d220, 0x000000000023ac7d))
```

- llvm12, -OReleaseSafe
```diff
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("zig 0.0.8")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name    ("s1")
              DW_AT_stmt_list   (0x00000000)
              DW_AT_comp_dir    (".")
              DW_AT_GNU_pubnames    (true)
              DW_AT_low_pc  (0x0000000000000000)
              DW_AT_ranges  (0x000127a0
                 [0x0000000000217f00, 0x0000000000217f2f)
                 [0x0000000000217f30, 0x0000000000218882)
                 [0x0000000000218890, 0x00000000002188dd)
                 [0x0000000000218910, 0x0000000000218944)
                 [0x0000000000218950, 0x00000000002189ee)
                 [0x0000000000218a60, 0x0000000000218ba4)
                 [0x0000000000203040, 0x00000000002033e8)
                 [0x00000000002033f0, 0x0000000000203a3f)
                 [0x0000000000203a40, 0x00000000002040ba)
                 [0x00000000002040c0, 0x0000000000204165)
                 [0x0000000000204170, 0x0000000000204346)
                 [0x0000000000204350, 0x000000000020dc3b)
                 [0x000000000020dc40, 0x0000000000217020)
                 [0x0000000000217020, 0x0000000000217efb))
```

**Comment by mikdusan** [comment]
- fixed and merged to llvm 12 branch; no need to merge on master
- tested on linux/macos/freebsd
- windows testing n/a; `ReleaseSafe` disabled even on master (llvm 11)

**Comment by LemonBoy** [comment]
Great detective work!
I've completely missed that its the line numbers that were missing and not the stack trace being truncated, the proposal to enable the frame pointer in safe mode is still valid tho.

> fixed and merged to llvm 12 branch; no need to merge on master

Skipping the code review is a big no-no in my book.
Adding the `self.prev_address > 0` is making the check fail every first time the function is called thus skipping the first entry.

What's the sequence of `address`, `prev_address` and `target_address` for the failing case?

**Comment by mikdusan** [comment]
> Skipping the code review is a big no-no in my book.

agreed. re-opened.

**Comment by mikdusan** [comment]
> Adding the self.prev_address > 0 is making the check fail every first time the function is called thus skipping the first entry.

It makes sense to skip it the way the code is setup - success returns previous iteration values for file,line,col. Skipping 0 also avoids undefined values which in debug/safe builds manifest as `error.InvalidDebugInfo` and fast/small are UB.

And although this is an improvement, it appears the status-quo logic for `checkLineMatch` is broken for:
- out of order ranges
- non-contiguous range

Consider 3 pseudo ranges: `[10..20] [80..90] [40..50]`
- we seek to find `43`
- on jump to `[80..90]` it will be a false-positive: `43 >= 20 and 43 < 80`

perhaps the code needs to handle 2 cases:
1. if compilation unit has 1 pcrange, then existing logic is ok
2. otherwise cu is non-contiguous and range-entries may be out of order and requires foreach range-entries and apply existing logic

**Comment by LemonBoy** [comment]
Can you upload the binary somewhere? I'm not able to build stage1 anymore as the OOM killer is killing the stage1 every time even though there are 12GB of free RAM.

Without seeing the opcodes in the `AT_stmt_list` section I'm still not sure if adding that check is ok or not.

**Comment by mikdusan** [comment]
> Can you upload the binary somewhere

zig.exe built from llvm12 branch: [gdrive](https://drive.google.com/file/d/1l6X4yWtwwAPAgzgz8MXws1upw7Dzab_h/view?usp=sharing)

**Comment by LemonBoy** [comment]
Oh I meant the executable built from `s1.zig` with `-ReleaseSafe` and the wonky DWARF infos, sorry for the confusion.

**Comment by mikdusan** [comment]
if you haven't checked, I used a slightly deeper stack `s2.zig` and both debug/safe exe are there too

**Comment by LemonBoy** [comment]
> if you haven't checked, I used a slightly deeper stack s2.zig and both debug/safe exe are there too

For some reason the tar I had downloaded was corrupt, re-downloading it fixed the problem.

You were half-right about where the problem is.
The `AT_ranges` list is traversed without assuming the ranges are sorted, that's not the problem.

Here you want to dump the line number directives (with `llvm-dwarfdump-12 -v -debug-line s2.safe` or your favourite tools):
the first address described in there is `0x2141a0`, searching for an address in the `0x20XXXX` range caused `checkLineMatch` to enter the `if` statement (`prev_address` is 0) and read a whole lot of garbage.

> And although this is an improvement, it appears the status-quo logic for checkLineMatch is broken for both:

The program counters within a compilation unit are monotonically increasing, if you check out the `dwarfdump` output you'll see that once the CU ends LLVM emits a `DW_LNE_end_sequence` to reset the interpreter.

We only need to make the PC check more robust when called the very first time, I'd avoid the `self.prev_address > 0` as that's pretty opaque and instead add a `bool` flag to guard the `prev_` fields validity. We could also make all of them optionals and pay the (small) price of extra space hit (that could be partially recovered by dropping unused `prev_` fields).
