### ISSUE TITLE
OS Error : Zig Source Code Cannot Compile From Android

### ISSUE THREAD

**Issue by amm834** [ziglang/zig#8765]
When I compile `zig` from source code , I'm facing `spawn.h` file not found error.
```sh
/data/data/com.termux/files/home/zig-0.8.0-dev.2224+459c9f053/src/stage1/os.cpp:60:10: 
fatal error: 'spawn.h' file not found
#include <spawn.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/zigstage1.dir/build.make:258: CMakeFiles/zigstage1.dir/src/stage1/os.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:121: CMakeFiles/zigstage1.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by ehaas** [comment]
Based on `com.termux` in your command line I'm guessing you're on Android. I don't know how well that is supported, but it looks like [you need to install libandroid-spawn](https://github.com/termux/termux-packages/issues/4634)

**Comment by amm834** [comment]
`libspawn` error was fixed by installing `libandroid-spawn` in Termux.
Now, I am facing second issue.

```sh
➜  build make install
[ 77%] Built target embedded_softfloat
[ 79%] Built target opt_c_util
[ 83%] Built target zigcpp
[ 97%] Built target zigstage1
[ 99%] Built target zig0
[ 99%] Building self-hosted component /data/data/com.termux/files/home/zig-0.8.0-dev.2224+459c9f053/build/zig1.o                            ./lib/std/c/linux.zig:181:13: error: reached unreachable code
    else => unreachable,
            ^
./lib/std/c/linux.zig:173:34: note: referenced here
const __SIZEOF_PTHREAD_MUTEX_T = if (builtin.os.tag == .fuchsia) 40 else switch (builtin.abi) {
                                 ^
./lib/std/c/linux.zig:137:12: note: referenced here
    size: [__SIZEOF_PTHREAD_MUTEX_T]u8 align(@alignOf(usize)) = [_]u8{0} ** __SIZEOF_PTHREAD_MUTEX_T,
           ^                                                          ./lib/std/Thread/Mutex.zig:178:5: note: while checking this field
    pthread_mutex: std.c.pthread_mutex_t = .{},
    ^
./lib/std/Thread/Mutex.zig:29:1: note: while checking this field
impl: Impl = .{},
^                                                                     ./lib/std/Progress.zig:60:1: note: while checking this field
update_lock: std.Thread.Mutex = .{},
^
make[2]: *** [CMakeFiles/zig.dir/build.make:339: zig1.o] Error 1      make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/zig.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
➜  build
```

**Comment by Vexu** [comment]
That should be fixed with https://github.com/ziglang/zig/issues/8384#issuecomment-810242900.

**Comment by amm834** [comment]
I am tried by adding `.android => if (@sizeOf(usize) ==  8) 56 else 40,` to my `lib/std/c/linux.z` like below.
````zig
172 const __SIZEOF_PTHREAD_COND_T = 48;
173 const __SIZEOF_PTHREAD_MUTEX_T = if (builtin.os.tag == .fuchsia) 40 else switch (builtin.abi) {
174   .android => if (@sizeOf(usize) == 8) 56 else 40,
175     .musl, .musleabi, .musleabihf => if (@sizeOf(usize) == 8) 40 else 24,
176     .gnu, .gnuabin32, .gnuabi64, .gnueabi, .gnueabihf, .gnux32 => switch (builtin.arch) {
177         .aarch64 => 48,
178         .x86_64 => if (builtin.abi == .gnux32) 40 else 32,
179         .mips64, .powerpc64, .powerpc64le, .sparcv9 => 40,
180         else => if (@sizeOf(usize) == 8) 40 else 24,
181     },
182     else => unreachable,
183 };
```
I got another error.

```sh
[ 99%] Built target zig0
[ 99%] Building self-hosted component /data/data/com.termux/files/home/zig-0.8.0-dev.2224+459c9f053/build/zig1.o
make[2]: *** [CMakeFiles/zig.dir/build.make:339: zig1.o] Killed
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/zig.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
➜  build ..
➜  zig-0.8.0-dev.2224+459c9f053 vi  lib/std/c/linux.zig
Error detected while processing /data/data/com.termux/files/home/.vimrc:                line    2:
E488: Trailing characters: set relativenumber: #set relativenumber

line    8:
```

**Comment by g-w1** [comment]
This seems like it is an OOM because building stage1 takes a lot of memory right now.

**Comment by amm834** [comment]
Yes, I know building something from source codes take long time but this is not too big.
What I am facing is that the `Cmake` error.
They support `aarch64` architecture but not working in my `aarch64` Android device.

**Comment by amm834** [comment]
Finally I got `zig0` binary file.
But I am still getting the Cmake error.

```sh
➜  build ls
 builtin.zig           CMakeFiles   Makefile
 cmake_install.cmake   config.h     zig0
 CMakeCache.txt        config.zig   zigcpp
```
Cmake error is still working.

```sh
➜  build make
Consolidate compiler generated dependencies of target embedded_softfloat
[ 77%] Built target embedded_softfloat
Consolidate compiler generated dependencies of target opt_c_util
[ 79%] Built target opt_c_util
Consolidate compiler generated dependencies of target zigcpp
[ 83%] Built target zigcpp
Consolidate compiler generated dependencies of target zigstage1
[ 97%] Built target zigstage1
Consolidate compiler generated dependencies of target zig0
[ 98%] Linking CXX executable zig0
[ 99%] Built target zig0
[ 99%] Building self-hosted component /data/data/com.termux/files/home/zig-0.8.0-dev.2224+459c9f053/build/zig1.o
make[2]: *** [CMakeFiles/zig.dir/build.make:339: zig1.o] Killed
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/zig.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

But I am confusing the `zip0` binary's usage.

```sh
➜  build ./zig0 --help
Usage: ./zig0 [options]            builds an object file

Options:
  --color [auto|off|on]        enable or disable colored error messages
  --name [name]                override output name
  -femit-bin=[path]            Output machine code
  --pkg-begin [name] [path]    make pkg available to import and push current pkg
  --pkg-end                    pop current pkg
  -ODebug                      build with optimizations on and safety off
  -OReleaseFast                build with optimizations on and safety off
  -OReleaseSafe                build with optimizations on and safety on
  -OReleaseSmall               build with size optimizations on and safety off
  --single-threaded            source may assume it is only used single-threaded
  -dynamic                     create a shared library (.so; .dll; .dylib)
  --strip                      exclude debug symbols
  -target [name]               <arch>-<os>-<abi> see the targets command
  -mcpu [cpu]                  specify target CPU and feature set
  --verbose-tokenize           enable compiler debug output for tokenization
  --verbose-ast                enable compiler debug output for AST parsing
  --verbose-ir                 enable compiler debug output for Zig IR
  --verbose-llvm-ir            enable compiler debug output for LLVM IR
  --verbose-cimport            enable compiler debug output for C imports
  --verbose-llvm-cpu-features  enable compiler debug output for LLVM CPU features

➜  build
```
The `zig0` cannot run the `main.zig` source  codes.

**Comment by g-w1** [comment]
Yes, zig0 is the c++ compiler. For the build to complete, zig0 has to compile the zig source codes to make zig1.o and then link together to make `zig`. The reason I think you are encountering an OOM is that from my experience, zig needs ~8gb of ram to build and I do not think phones have that much ram. It seems the android OOM killer is killing the build. `make[2]: *** [CMakeFiles/zig.dir/build.make:339: zig1.o] Killed`.

**Comment by amm834** [comment]
Having more RAM is not good idea for Android.
I found similar issue  likes
my issue. 
https://github.com/ziglang/zig/issues/6485
It should be fix but not.
So, `zig` should support compiled binary file  for Android device.

**Comment by wozeparrot** [comment]
Does the aarch64-linux master binary here: https://ziglang.org/download/ not work?
Last time I used zig on termux the aarch64 binary works fine.

**Comment by amm834** [comment]
> Does the aarch64-linux master binary here: https://ziglang.org/download/ not work?
> Last time I used zig on termux the aarch64 binary works fine.

It's working now,thank you.

**Comment by leapofazzam123** [comment]
Why did this man gave up and just used the pre built version

**Comment by leapofazzam123** [comment]
Can someone reopen this issue, I'm doing a Zig PR at termux/termux-packages#7990
